### ISSUE TITLE
Error if you specify a dir with ending /

### ISSUE THREAD

**Issue by nukeador** [mozilla/sumo-mt#2]
Using --dir if your folder has an ending /, the script will fail with a DNS error.

```
 ./mediawiki.py --dir ../exports/desktop/ --lang 'nl'
Traceback (most recent call last):
  File "./mediawiki.py", line 265, in <module>
    main()
  File "./mediawiki.py", line 251, in main
    outputLanguage = currentLang)
  File "/home/nuke/bin/sumo-mt/script/WikiParser.py", line 78, in __init__
    self.parseMediaWikiFile()
  File "/home/nuke/bin/sumo-mt/script/WikiParser.py", line 218, in parseMediaWikiFile
    target_language_code=self.mOutputLanguage)
  File "/home/nuke/.local/lib/python2.7/site-packages/google/cloud/translate_v3beta1/gapic/translation_service_client.py", line 300, in translate_text
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/home/nuke/.local/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/nuke/.local/lib/python2.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/home/nuke/.local/lib/python2.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/home/nuke/.local/lib/python2.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/home/nuke/.local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/home/nuke/.local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
google.api_core.exceptions.ServiceUnavailable: 503 DNS resolution failed
```

**Comment by nukeador** [comment]
I tested this with a folder a 2 files and works, so maybe the problem is not just the ending / but also having a folder with a lot of files or files with specific names?

This happened with a folder and a lot of files

![image](https://user-images.githubusercontent.com/531906/57475658-0882e380-7295-11e9-914f-0cb8b7a4748b.png)
